version: '2'
services:
  web:
    build: .
    env_file: .env
    volumes:
      - ./app:/var/www/symfony
    ports:
      - "80:80"
    links:
      - mysql
    environment:
      SYMFONY_DEBUG: 1
      SYMFONY_ENV: dev
      LOG_LEVEL: debug
      DATABASE_DSN: "mysql://root:ThisIsNotASecurePassword123@mysql/celebrate"

  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: "ThisIsNotASecurePassword123"
      MYSQL_DATABASE: "celebrate"
    ports:
      - 3306:3306
    expose:
      - 3306
