imports:
    - { resource: parameters.yml }
    - { resource: parameters.php }

framework:
    secret: %secret%
    assets: ~
    templating:
        engines: ['twig']

# Doctrine Configuration
doctrine:
    dbal:
        url: "%env(DATABASE_DSN)%"
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
